background            #171723
foreground            #bdc9f1

# black
color0  #171723
color8  #383948

# red
color1  #f17598
color9  #f17598

# green
color2  #93dd8d
color10 #93dd8d

# yellow
color3  #f7d997
color11 #f7d997

# blue
color4  #71a5f9
color12 #71a5f9

# magenta
color5  #bd8df5
color13 #bd8df5

#cyan
color6  #84decf
color14 #84decf

#white
color7  #bdc9f1
color15 #ffffff


